# Project information
site_name: REPO_NAME_OR_SITE_NAME
# defeine TOC or order of website-
nav:
  - Home: index.md
  - Feedback: feedback.md

site_author: Sunny Bhaveen Chandra
site_description: >-
  DESCRIPTION

# Repository
repo_name: Gokul-Marudhasalam/pytorchbasics
repo_url: https://github.com/Gokul-Marudhasalam/pytorchbasics.git

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Gokul-Marudhasalam    
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/gokulmarudhasalam/
    

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.arithmatex
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/c17hawke"  target="_blank" rel="noopener">Sunny Bhaveen Chandra</a>
